version: 0.1

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package -P prod
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - roommate-application/target/roommate-application.jar
  discard-paths: yes