# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "release/mvp1" ]
  pull_request:
    branches: [ "release/mvp1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package -P dev

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        source: "roommate-application.jar"
        target: "~/source"
    - name: Start service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          sudo /etc/init.d/roommate-application stop
          mv ~/source/roommate-application.jar ~/source/roommate-application-old.jar
          mv ~/source/roommate-application-latest.jar ~/source/roommate-application.jar
          sudo rm -rf /etc/init.d/roommate-application
          sudo ln -s -f ~/source/roommate-application.jar /etc/init.d/roommate-application
          sudo /etc/init.d/roommate-application start
          rm ~/source/roommate-application-old.jar