server:
  port: 5000

spring:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: never # data.sql
  datasource:
    url: jdbc:postgresql://database-1.cob8cnmwobcc.eu-west-2.rds.amazonaws.com/roommate_dev
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect